# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('username', models.CharField(blank=True, db_column='USERNAME', max_length=31, null=True)),
                ('entered', models.DateTimeField(blank=True, db_column='ENTERED', null=True)),
                ('voided', models.DateTimeField(blank=True, db_column='VOIDED', null=True)),
                ('run', models.IntegerField(blank=True, db_column='RUN', null=True)),
                ('shot', models.IntegerField(blank=True, db_column='SHOT', null=True)),
                ('topic', models.CharField(db_column='TOPIC', max_length=16)),
                ('text', models.TextField(blank=True, db_column='TEXT', null=True)),
                ('dbkey', models.IntegerField(db_column='DBKEY', primary_key=True, serialize=False)),
                ('guid', models.CharField(blank=True, db_column='GUID', max_length=36, null=True)),
            ],
            options={
                'db_table': 'ENTRIES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntryDisplayPrefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('last_saved', models.DateTimeField()),
                ('run', models.IntegerField()),
                ('topics', models.CharField(max_length=2000)),
                ('user_select', models.CharField(max_length=20)),
                ('show_voided', models.CharField(max_length=1)),
                ('sort_by_shot', models.BooleanField()),
                ('ascending', models.BooleanField()),
                ('null_shots_first', models.BooleanField()),
                ('auto_update', models.BooleanField()),
                ('auto_scroll', models.BooleanField()),
                ('scroll_top', models.BooleanField()),
                ('max_rows', models.SmallIntegerField()),
                ('fontsize', models.SmallIntegerField(blank=True, null=True)),
                ('show_test', models.CharField(blank=True, max_length=1, null=True)),
                ('guid', models.CharField(blank=True, db_column='GUID', max_length=36, null=True)),
            ],
            options={
                'db_table': 'ENTRY_DISPLAY_PREFS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntryDisplayTemplates',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('template_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('entered', models.DateTimeField()),
                ('global_field', models.NullBooleanField(db_column='global')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, max_length=16, null=True)),
                ('guid', models.CharField(blank=True, db_column='GUID', max_length=36, null=True)),
            ],
            options={
                'db_table': 'ENTRY_DISPLAY_TEMPLATES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Miniproposals',
            fields=[
                ('mp', models.IntegerField()),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_filed', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(max_length=20)),
                ('file_date', models.CharField(blank=True, max_length=64, null=True)),
                ('icrf_80_mhz', models.SmallIntegerField(blank=True, db_column='ICRF_80_MHz', null=True)),
                ('icrf_70_mhz', models.SmallIntegerField(blank=True, db_column='ICRF_70_MHz', null=True)),
                ('icrf_50_mhz', models.SmallIntegerField(blank=True, db_column='ICRF_50_MHz', null=True)),
                ('cryopump', models.SmallIntegerField(blank=True, db_column='Cryopump', null=True)),
                ('dnb', models.SmallIntegerField(blank=True, db_column='DNB', null=True)),
                ('rev_b', models.SmallIntegerField(blank=True, db_column='rev_B', null=True)),
                ('high_b', models.SmallIntegerField(blank=True, db_column='high_B', null=True)),
                ('boronize_overnight', models.SmallIntegerField(blank=True, null=True)),
                ('boronize_shots', models.SmallIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('guid', models.CharField(blank=True, db_column='GUID', max_length=36, null=True)),
            ],
            options={
                'db_table': 'Miniproposals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('first_shot', models.IntegerField()),
                ('last_shot', models.IntegerField()),
                ('run', models.IntegerField(blank=True, null=True)),
                ('job', models.CharField(max_length=2)),
                ('active', models.BooleanField()),
                ('brief', models.CharField(blank=True, max_length=256, null=True)),
                ('mp', models.IntegerField(blank=True, null=True)),
                ('guid', models.CharField(blank=True, db_column='GUID', max_length=36, null=True)),
            ],
            options={
                'db_table': 'Operators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=31)),
                ('application', models.CharField(max_length=30)),
                ('item', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=1000)),
                ('guid', models.CharField(blank=True, db_column='GUID', max_length=36, null=True)),
            ],
            options={
                'db_table': 'PREFERENCES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='USERNAME', max_length=31)),
                ('entered', models.DateTimeField(db_column='ENTERED')),
                ('run', models.IntegerField(db_column='RUN')),
                ('brief', models.CharField(blank=True, db_column='BRIEF', max_length=72, null=True)),
                ('dbkey', models.IntegerField(db_column='DBKEY')),
                ('guid', models.CharField(blank=True, db_column='GUID', max_length=36, null=True)),
            ],
            options={
                'db_table': 'RUNS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='USERNAME', max_length=31)),
                ('entered', models.DateTimeField(db_column='ENTERED')),
                ('run', models.IntegerField(db_column='RUN')),
                ('shot', models.IntegerField(db_column='SHOT')),
                ('brief', models.CharField(blank=True, db_column='BRIEF', max_length=72, null=True)),
                ('plasma_shot', models.CharField(blank=True, db_column='PLASMA_SHOT', max_length=1, null=True)),
                ('quality_comment', models.CharField(blank=True, db_column='QUALITY_COMMENT', max_length=72, null=True)),
                ('shot_ok', models.SmallIntegerField(blank=True, db_column='SHOT_OK', null=True)),
                ('total_uncompressed_size', models.FloatField(blank=True, db_column='TOTAL_UNCOMPRESSED_SIZE', null=True)),
                ('total_compressed_size', models.FloatField(blank=True, db_column='TOTAL_COMPRESSED_SIZE', null=True)),
                ('total_uncompressed_umn', models.FloatField(blank=True, db_column='TOTAL_UNCOMPRESSED_UMN', null=True)),
                ('total_compressed_umn', models.FloatField(blank=True, db_column='TOTAL_COMPRESSED_UMN', null=True)),
                ('total_uncompressed', models.FloatField(blank=True, db_column='TOTAL_UNCOMPRESSED', null=True)),
                ('total_compressed', models.FloatField(blank=True, db_column='TOTAL_COMPRESSED', null=True)),
                ('init_time', models.FloatField(blank=True, db_column='INIT_TIME', null=True)),
                ('store_time', models.FloatField(blank=True, db_column='STORE_TIME', null=True)),
                ('analysis_time', models.FloatField(blank=True, db_column='ANALYSIS_TIME', null=True)),
                ('dbkey', models.IntegerField(db_column='DBKEY')),
                ('nodata', models.NullBooleanField(db_column='NODATA')),
                ('guid', models.CharField(blank=True, db_column='GUID', max_length=36, null=True)),
            ],
            options={
                'db_table': 'SHOTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_column='USERNAME', max_length=31, null=True)),
                ('entered', models.DateTimeField(blank=True, db_column='ENTERED', null=True)),
                ('topic', models.CharField(db_column='TOPIC', max_length=16)),
                ('brief', models.CharField(db_column='BRIEF', max_length=72)),
                ('dbkey', models.IntegerField(db_column='DBKEY')),
                ('sort_order', models.IntegerField(blank=True, db_column='SORT_ORDER', null=True)),
            ],
            options={
                'db_table': 'TOPICS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('po', models.BooleanField(db_column='PO')),
                ('eo', models.BooleanField(db_column='EO')),
                ('active', models.BooleanField()),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('crphone', models.CharField(blank=True, max_length=50, null=True)),
                ('pager', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('fullname', models.CharField(blank=True, max_length=101, null=True)),
                ('hidden', models.BooleanField()),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('guid', models.CharField(blank=True, db_column='GUID', max_length=36, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
