# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbookapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('username', models.CharField(db_column='USERNAME', max_length=31)),
                ('entered', models.DateTimeField(db_column='ENTERED')),
                ('run', models.IntegerField(db_column='RUN')),
                ('shot', models.IntegerField(db_column='SHOT')),
                ('brief', models.CharField(blank=True, db_column='BRIEF', max_length=72, null=True)),
                ('plasma_shot', models.CharField(blank=True, db_column='PLASMA_SHOT', max_length=1, null=True)),
                ('quality_comment', models.CharField(blank=True, db_column='QUALITY_COMMENT', max_length=72, null=True)),
                ('shot_ok', models.SmallIntegerField(blank=True, db_column='SHOT_OK', null=True)),
                ('total_uncompressed_size', models.FloatField(blank=True, db_column='TOTAL_UNCOMPRESSED_SIZE', null=True)),
                ('total_compressed_size', models.FloatField(blank=True, db_column='TOTAL_COMPRESSED_SIZE', null=True)),
                ('total_uncompressed_umn', models.FloatField(blank=True, db_column='TOTAL_UNCOMPRESSED_UMN', null=True)),
                ('total_compressed_umn', models.FloatField(blank=True, db_column='TOTAL_COMPRESSED_UMN', null=True)),
                ('total_uncompressed', models.FloatField(blank=True, db_column='TOTAL_UNCOMPRESSED', null=True)),
                ('total_compressed', models.FloatField(blank=True, db_column='TOTAL_COMPRESSED', null=True)),
                ('init_time', models.FloatField(blank=True, db_column='INIT_TIME', null=True)),
                ('store_time', models.FloatField(blank=True, db_column='STORE_TIME', null=True)),
                ('analysis_time', models.FloatField(blank=True, db_column='ANALYSIS_TIME', null=True)),
                ('dbkey', models.IntegerField(db_column='DBKEY')),
                ('nodata', models.NullBooleanField(db_column='NODATA')),
                ('guid', models.CharField(blank=True, db_column='GUID', max_length=36, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SHOTS',
                'managed': False,
            },
        ),
    ]
